# Generated by Django 3.0.8 on 2021-12-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(default='01/01/1970'),
        ),
    ]
