# Generated by Django 3.0.8 on 2022-03-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral_api', '0003_auto_20211217_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('articleAddress', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=100)),
                ('journal', models.CharField(max_length=100)),
            ],
        ),
    ]
