# Generated by Django 3.0.8 on 2022-03-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral_api', '0004_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='tag',
            field=models.CharField(default='def', max_length=100),
            preserve_default=False,
        ),
    ]
