# Generated by Django 4.0.4 on 2022-05-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viral_api', '0006_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='tag',
            new_name='cmd_arg',
        ),
    ]
